Second task
katerinarodnykh/cyber-project pull request #3
Opened 2022-02-06 23:29 UTC by Sakharov1998

Added all the fonts to the project.
Tested them, using text-phrases.
Added var in style.css
Coloured some text.

2022-02-07 13:40 UTC, katerinarodnykh requested changes

2022-02-07 13:40 UTC, katerinarodnykh commented on css/style.css
> +    url("css/fonts/ProximaNova-Black.ttf") format("ttf"),
папка fonts уже была создана, она лежит не в папке css. В css только стилевые файлы, нужно перенести

2022-02-07 13:40 UTC, katerinarodnykh commented on css/style.css
> +.text__proxima-black{
пробел между классом и скобкой

2022-02-07 13:40 UTC, katerinarodnykh commented on css/style.css
> +
зачем нам тут такой большой отступ? весь код идёт подряд, лишних пробелов быть не должно

2022-02-07 13:40 UTC, katerinarodnykh commented on index.html
> +    <span class="text__proxima-black">Text 1</span>
![image](https://user-images.githubusercontent.com/30826614/152797556-43bbba57-c9f5-45e3-9472-527576873985.png)
браузер пишет мне, что используемый шрифт: helvetica. Проверь везде, я не вижу чтобы шрифты были подключены

2022-02-07 13:40 UTC, katerinarodnykh commented on css/style.css
> +    url("css/fonts/ProximaNova-Extrabld.woff") format("woff"),
в названии пропущена буква

2022-02-07 13:40 UTC, katerinarodnykh commented on css/style.css
> +    url("css/fonts/ProximaNova-SemiboldIt.woff2") format("woff2");
почему название для woff2 отличается?

2022-02-07 13:40 UTC, katerinarodnykh commented on css/style.css
> +    url("css/fonts/ProximaNova-Black.woff2") format("woff2");
почему файлы шрифта подключаются не в нужно последовательности? проверь ещё раз как написано в примере

2022-02-07 14:04 UTC, Sakharov1998 commented on css/style.css
> +    url("css/fonts/ProximaNova-Black.ttf") format("ttf"),
То есть папка fonts была создана в самом начале проекта? Я немного не понял комментария. Не могли бы ты разъяснить немного подробнее, пожалуйста.

2022-02-07 14:07 UTC, Sakharov1998 commented on css/style.css
> +    url("css/fonts/ProximaNova-Black.ttf") format("ttf"),
Я ведь создал папку fonts при скачивании шрифтов. В изначальном проекте, с которого делал fork, не было такой папки. Или я думаю не в ту сторону...

2022-02-07 14:09 UTC, Sakharov1998 commented on css/style.css
> +.text__proxima-black{
Исправил

2022-02-07 14:10 UTC, Sakharov1998 commented on css/style.css
> +
Исправил. Забыл, что у нас еще есть .red

2022-02-07 14:15 UTC, katerinarodnykh commented on css/style.css
> +    url("css/fonts/ProximaNova-Black.ttf") format("ttf"),
Папка была создана мной изначально, как на одном уровне дежат папки css, img, fonts, чтобы ты пользовался этой структурой

2022-02-10 00:05 UTC, Sakharov1998 reviewed
Corrected all the fonts information and reconnected them.
Also corrected some syntax in css.

2022-02-10 08:30 UTC, katerinarodnykh requested changes

2022-02-10 08:30 UTC, katerinarodnykh commented on index.html
> +    <span class="text__proxima_semibold">Text 4</span>
для этого текста подтягивается начертание italic: rendered fonts - Proxima Nova Semibold Italic, хотя у тебя прописан normal. Что в итоге должно быть верно? 
![image](https://user-images.githubusercontent.com/30826614/153367480-661a8871-c182-4ad8-aa20-c13bd1442024.png)

2022-02-10 10:51 UTC, Sakharov1998 commented on index.html
> +    <span class="text__proxima_semibold">Text 4</span>
<img width="415" alt="Снимок экрана 2022-02-10 в 13 49 16" src="https://user-images.githubusercontent.com/98780742/153391823-2c7676cf-9f6e-43c9-94c7-48568ad52a1b.png">

Я добавил другой шрифт, скачал Proxima Nova Semibold с другого сайта. Везде проверил свойства - прописано normal. Тем не менее браузер рендерит шрифт, как italic, скриншот того, что шрифт полужирный и не наклонный прилагается (открыл файл .ttf).

2022-02-10 10:52 UTC, Sakharov1998 commented on index.html
> +    <span class="text__proxima_semibold">Text 4</span>
Верный вариант - normal, наклонный вариант в макете не указан

2022-02-10 11:18 UTC, merged