added-html-img-and-some-css
katerinarodnykh/cyber-project pull request #4
Opened 2022-02-11 11:55 UTC by Sakharov1998

Wrote html, added svg images and some css code.

2022-02-12 14:45 UTC, Sakharov1998 commented
Почти завершил header, осталось только еще сделать отступы для pixel perfect. Сделал тестовый hover для пунктов меню. Работаю далее.

2022-02-12 19:33 UTC, katerinarodnykh requested changes

2022-02-12 19:33 UTC, katerinarodnykh commented on css/style.css
> +    padding: 0;
нет смысла писать и в html и в body и каждый раз сбрасывать отступы, посмотри как сброшены эти параметры для всех элементов на сайте-примере

2022-02-12 19:33 UTC, katerinarodnykh commented on css/style.css
> +    background-color: #000000;
в прошлом задании ты тренировался писать css-переменные для цветов, чтобы в третьем их не использовать?

2022-02-12 19:33 UTC, katerinarodnykh commented on css/style.css
> +    position: absolute;
абсолютное позиционирование применяется только в декоративных элементов или если нет другого способа реализовать дизайн, убираем свойство

2022-02-12 19:33 UTC, katerinarodnykh commented on css/style.css
> +}
отступ

2022-02-12 19:33 UTC, katerinarodnykh commented on css/style.css
> +    margin-right: 122.96px;
только целочисленные значения

2022-02-12 19:33 UTC, katerinarodnykh commented on css/style.css
> +    max-width: 512px;
меню - это динамический элемент, пункты могут быть убраны/добавлены ещё, поэтому у меню обычно не фиксируется какая-либо ширина

2022-02-12 19:33 UTC, katerinarodnykh commented on css/style.css
> +    height: 170px;
если убрать это свойство, то ничего не изнменится, в таком случае свойство - лишнее

2022-02-12 19:33 UTC, katerinarodnykh commented on css/style.css
> +    margin-left: 48px;
вместо таких отступов прочитай про свойство gap

2022-02-12 19:33 UTC, katerinarodnykh commented on css/style.css
> +    background-color: #2200E4;
как мы обсуждали на созвоне синий фон это не только наведение, но и активный пункт меню

2022-02-12 19:33 UTC, katerinarodnykh commented on css/style.css
> +    background-color: #2200E4;
синий фон это только для меню, тут не нужен. Обрати внимание, что ссылки надо делать, таким образом, чтобы их удобно было нажимать. Если человек немного промахнулся мышкой, чтобы это не момешало ссылке сработать, поэтому для ссылок добавляются отступы вокруг. Чтобы увеличить область нажатия

2022-02-12 19:33 UTC, katerinarodnykh commented on index.html
> +       <main class="content">
разметка основных блоков header, footer, main сделана неверно

2022-02-12 19:33 UTC, katerinarodnykh commented on index.html
> +               <div class="header__logo">
этот элемент сам можно сделать ссылкой

2022-02-12 19:33 UTC, katerinarodnykh commented on index.html
> +                       <img src="img/logo.svg" alt="federation-logo">
прочитай про alt и зачем он нужен, для картинок прописывам атрибуты width и height.
У каждого элемента пишем класс. Чтобы в дальнейшем, если с ним нужно будет поработать, не нужно было ничего дописывать. Классы пиши, пожалуйста, в начале.

2022-02-12 19:33 UTC, katerinarodnykh commented on index.html
> +                   <a href="#" class="navigation__link">
навигацию оформляем списком

2022-02-12 19:33 UTC, katerinarodnykh commented on index.html
> +                       <img src="img/home.svg" alt="home-icon" class="navigation__home">
нет необходимости писать свой индивидуальный класс каждому пункту меню, они все одинаковые, используем один единый класс

2022-02-13 20:24 UTC, Sakharov1998 commented on index.html
> +               <div class="header__logo">
Исправлено

2022-02-13 20:24 UTC, Sakharov1998 commented on index.html
> +                   <a href="#" class="navigation__link">
Исправлено

2022-02-13 20:24 UTC, Sakharov1998 commented on index.html
> +                       <img src="img/home.svg" alt="home-icon" class="navigation__home">
Исправлено

2022-02-13 20:45 UTC, Sakharov1998 commented on index.html
> +                       <img src="img/logo.svg" alt="federation-logo">
Прочитал информацию про правильное написание alt в шпаргалках html academy (https://htmlacademy.ru/blog/boost/frontend/alt-text),
width и height прописал у цветного логотипа и всех svg изображений,
прописал классы у всех элементов и переместил все классы в начало.

2022-02-13 20:49 UTC, Sakharov1998 commented on index.html
> +       <main class="content">
Поменял main на div, понял, что далее у нас будет сама страница, которая как раз и будет являться main'ом. Сделал отдельный класс div.page, чтобы отразить на нем всю страницу

2022-02-13 20:50 UTC, Sakharov1998 commented on css/style.css
> +    margin-right: 122.96px;
Исправлено. Вопрос: для точности разметки в какую сторону лучше округлять нецелые числа? По базовым правилам математики?

2022-02-13 20:52 UTC, Sakharov1998 commented on css/style.css
> +}
Исправлено. Сделано целочисленное значение.

2022-02-13 21:11 UTC, katerinarodnykh commented on css/style.css
> +    margin-right: 122.96px;
да, по правилам

2022-02-13 21:14 UTC, katerinarodnykh commented on index.html
> +       <main class="content">
не понимаю о чём речь, я про это https://htmlacademy.ru/courses/299/run/1, про самые основые, любые контейнеры уже помещаем внутрь этих тегов

2022-02-13 21:21 UTC, Sakharov1998 commented on css/style.css
> +    background-color: #000000;
Переменные добавлены. Вопрос: как нужно ли верстальщику подбирать реальные названия всем цветам? Потому что без точных названий затруднительно.

2022-02-13 21:39 UTC, Sakharov1998 commented on css/style.css
> +    padding: 0;
Сверился с сайтом-примером и взял оттуда стили для html и body

2022-02-13 22:06 UTC, Sakharov1998 commented
Осталось сделать лучше наведение для ссылок, подправить нюансы. Я уже верстаю следующую часть - баннер, который откроет ссылку в новом окне

2022-02-13 22:11 UTC, Sakharov1998 commented on css/style.css
> +    background-color: #2200E4;
Добавлено

2022-02-13 22:11 UTC, Sakharov1998 commented on css/style.css
> +    background-color: #2200E4;
Для юзера убрал. Сейчас подправлю ссылки

2022-02-13 22:16 UTC, Sakharov1998 commented on index.html
> +       <main class="content">
На сайте примере сначала идет body, затем идет body__container, далее уже идут все семантические теги, вроде header, main и т.д. Или я неверно понял?

2022-02-13 22:18 UTC, Sakharov1998 commented on css/style.css
> +    max-width: 512px;
Убрал фиксированную ширину. А как же работа по макету? Там указаны конкретные размеры блока меню

2022-02-13 22:19 UTC, Sakharov1998 commented on css/style.css
> +    height: 170px;
Исправил.

2022-02-13 22:21 UTC, Sakharov1998 commented on css/style.css
> +    margin-left: 48px;
Нашел материал про gap на MDN docs, сейчас изучу и исправлю отступы

2022-02-14 11:19 UTC, katerinarodnykh requested changes

2022-02-14 11:19 UTC, katerinarodnykh commented on css/style.css
> +    max-width: 512px;
там такая ширина, потому что на данный момент столько пунктов меню. На практике пункты меню меняются и часто добавляются относительно изначально макета

2022-02-14 11:19 UTC, katerinarodnykh commented on css/style.css
> +    overflow-x: hidden;
зачем тебе тут это свойство?

2022-02-14 11:19 UTC, katerinarodnykh commented on css/style.css
> +    border-style: none;
у картинок разве есть border по умолчанию, который тебе надо обнулять?

2022-02-14 11:19 UTC, katerinarodnykh commented on css/style.css
> +    list-style-type: none;
если убрать свойства flex-direction и list-style ничего не изменится, list-style: none; ты уже сбросил для списков ранее, а flex-direction: row; это свойство по умолчани. Убираем

2022-02-14 11:19 UTC, katerinarodnykh commented on index.html
> +                       <img src="img/logo.svg" alt="Цветной логотип федерации компьютерного спорта России" width="412px" height="166px">
атрибуты ширины и высоты пишутся без пикселей

2022-02-14 11:19 UTC, katerinarodnykh commented on index.html
> +                        <li class="navigation__list-item">
зачем тут двойное название класса во второй части, когда можно написать оно слово?

2022-02-14 11:19 UTC, katerinarodnykh commented on css/style.css
> +    --medium-blue: #2200E4;
"Переменные добавлены. Вопрос: как нужно ли верстальщику подбирать реальные названия всем цветам? Потому что без точных названий затруднительно."

Названия придумываются на усмотрение верстальщика, главное чтобы они отражали суть и тебе удобно было потом ими пользоваться

2022-02-14 11:19 UTC, katerinarodnykh commented on index.html
> +               <div class="header__content-top">
лишняя обёртка, без неё также можно получить нужный вид

2022-02-14 11:19 UTC, katerinarodnykh commented on index.html
> +       <div class="page">
здесь можем оставить эти контейнеры, я имела ввиду что у тебя был header был внутри main, это убрано и ок. Проверь, чтобы у тебя не было лишних свойств, убрав которые ничего не меняется

2022-02-14 12:01 UTC, Sakharov1998 commented on index.html
> +               <div class="header__content-top">
Без header__content-top,  я верно понял? Подсмотрел структуру на сайте-примере. Подумал, что такое деление будет более удачным.

2022-02-14 12:03 UTC, Sakharov1998 commented on css/style.css
> +    --medium-blue: #2200E4;
Понял. Нашел таблицу-шпаргалку для всех поддерживаемых цветов в спецификации. Будет удообнее задавать переменные. **Вопрос**: на каком этапе верстальщик задает переменные? По мере верстки блоков или на начальном этапе проработки макета, чтобы сразу зацепить все цвета и потом добавлять только переменные?

2022-02-14 12:06 UTC, Sakharov1998 commented on index.html
> +                        <li class="navigation__list-item">
Заменил название на navigation__item

2022-02-14 12:08 UTC, Sakharov1998 commented on index.html
> +                       <img src="img/logo.svg" alt="Цветной логотип федерации компьютерного спорта России" width="412px" height="166px">
Убрал в html пиксели, скорректировал

2022-02-14 12:09 UTC, Sakharov1998 commented on css/style.css
> +    list-style-type: none;
Исправлено.

2022-02-14 12:11 UTC, Sakharov1998 commented on css/style.css
> +    border-style: none;
Такого параметры нет, исправил. Подсматривал на сайте примере, думая, что это - базовый параметр обнуления для каждого макета.

2022-02-14 12:14 UTC, Sakharov1998 commented on css/style.css
> +    overflow-x: hidden;
Свойство убрал. **Вопрос**: я уже много вариантов перепробовал, но header у меня не растягивается на весь экран, несмотря на width:100%. Если приглядеться, слева и справа от него есть очень маленькие черные полоски. Помогал position:absolute от этого недуга. Как только убрал его, все вернулось на круги своя.

2022-02-14 12:45 UTC, katerinarodnykh requested changes

2022-02-14 12:45 UTC, katerinarodnykh commented on css/style.css
> +    --medium-blue: #2200E4;
по-хорошему я прошу дизайнера вынести все цвета в style-guide, это такой набор шрифтов, цветов и всего остального что встречается по всему сайту, потому что мне удобнее сразу всё прописать и потом использовать. В данном случае дизайнер просто ещё не сделала этот элемент, так что ты действуешь на своё усмотрение. Можно добавить разу, можно постепенно

2022-02-14 12:45 UTC, katerinarodnykh commented on css/style.css
> +    overflow-x: hidden;
не понимаю как связано это свойство для body с header, возможно посмотрим позже на созвоне что ты имеешь ввиду

2022-02-14 12:45 UTC, katerinarodnykh commented on css/style.css
> +    border-style: none;
такого нет на том сайте, который я скидывала в качестве примера

2022-02-14 16:45 UTC, Sakharov1998 commented
Пишу ответ на коммент, связанный с img, прилагаю скриншот, там в img есть. свойство, связанное с границей
<img width="1440" alt="Снимок экрана 2022-02-14 в 19 44 43" src="https://user-images.githubusercontent.com/98780742/153907850-f38d7695-ba78-4275-beca-139da7a21dee.png">

2022-02-14 16:55 UTC, Sakharov1998 commented on css/style.css
> +    margin-left: 48px;
Gap оказалось очень удобным и полезным свойством, спасибо! Получилось реализовать размеры точнее в меню и юзере.

2022-02-14 17:13 UTC, katerinarodnykh requested changes

2022-02-14 17:13 UTC, katerinarodnykh commented on index.html
> +                   <li class="navigation__item">
эм, откуда тут взялось navigation__item?

2022-02-14 17:13 UTC, katerinarodnykh commented on index.html
> +               <div class="header__content-top">
там совершенно другая структура и дизайн, удаляем

2022-02-14 17:30 UTC, katerinarodnykh requested changes

2022-02-14 17:30 UTC, katerinarodnykh commented on css/style.css
> +    padding: 10px;
отступ у всех ссылок плохая идея, у некоторых, как у логотипа этого нет, это прописывается конкретно у каждой ссылки

2022-02-14 17:33 UTC, Sakharov1998 commented on index.html
> +                   <li class="navigation__item">
Исправил.

2022-02-15 19:18 UTC, katerinarodnykh requested changes

2022-02-15 19:18 UTC, katerinarodnykh commented on css/style.css
> +    background: var(--black);
в макете же не чёрный цвет

2022-02-15 19:18 UTC, katerinarodnykh commented on css/style.css
> +    width: 100%;
в прошлом комментарии было к этим же блокам, что свойства при удалении которых ничего не меняется, не нужны. Не вижу, чтобы лишние свойства были удалены

2022-02-15 19:18 UTC, katerinarodnykh commented on css/style.css
> +    background-color: var(--light-black);
тот же комментарий про лишние свойства у шапки. Также у шапки в макете скругление, не вижу чтобы было реализовано, про отступ сверху говорили на созвоне, что надо добавить. Не вижу этих вещей

2022-02-15 19:18 UTC, katerinarodnykh commented on css/style.css
> +.header__item a {
ображение к элементам идёт по классам, у тебя же есть у ссылок класс

2022-02-15 19:18 UTC, katerinarodnykh commented on css/style.css
> +    height: 100%;
опять лишние свойства

2022-02-15 19:18 UTC, katerinarodnykh commented on css/style.css
> +.navigation__link {
почему опять слиплось?

2022-02-15 19:18 UTC, katerinarodnykh commented on css/style.css
> +    background-color: var(--medium-blue);
посмотри каким образом сделан active на сайте примере, при созвоне я говорила, что активный пункт меня добавляем с помощью модификатора

2022-02-15 19:18 UTC, katerinarodnykh commented on index.html
> +                 width="412" height="166">
всё в одну строчку у тега img

2022-02-15 19:18 UTC, katerinarodnykh commented on index.html
> +                             alt="Перейти на домашнюю страницу сайта">
где атрибуты ширины и высоты? у некоторых пунктов их нет

2022-02-15 19:18 UTC, katerinarodnykh commented on index.html
> +                <a class="user__link" href="#">
у поиска есть выделение кнопки, которое мы ещё обсуждали на созвоне. Не вижу его визуально в результате

2022-02-16 09:43 UTC, merged